userDetails:
  url: 'https://auth.ala.org.au/userdetails/'
  readTimeout: 0 # disable read timeouts for user details because some services are slooooow...
#name:
#main:
#version:
security:
  core:
    permissionsAttributes: ['scopes']
    authCookieName: ${security.cas.authCookieName}
  oidc:
    enabled: false
    clientId: 'ChangeMe'
    secret: 'ChangeMe'
    discoveryUri: 'https://auth.ala.org.au/cas/oidc/.well-known'
    scope: 'openid profile email ala roles'
  cas:
    casServerName: 'https://auth.ala.org.au'
    casServerUrlPrefix: 'https://auth.ala.org.au/cas'
    loginUrl: 'https://auth.ala.org.au/cas/login'
    logoutUrl: 'https://auth.ala.org.au/cas/logout'
    bypass: false
    gateway: false
    renew: false
    encodeServiceUrl: true
    uriFilterPattern: ['/admin/*','/testAuth','/authTest/*']
    uriExclusionFilterPattern: []
    authenticateOnlyIfLoggedInPattern: []
    authenticateOnlyIfLoggedInFilterPattern: ['/']
    gatewayFilterPattern: []
    gatewayIfCookieFilterPattern: []
    gatewayStorageClass: 'org.jasig.cas.client.authentication.DefaultGatewayResolverImpl'
    roleAttribute: 'role'
    ignoreCase: true
    authCookieName: 'ALA-Auth'
