---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.ws
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'


---
# configuration for plugin testing - will not be included in the plugin zip
security:
    cas:
        service: 'http://localhost:8080'

environments:
    test:
        security:
            cas:
                service: 'http://localhost:8080'
