buildscript {
    repositories {
        mavenLocal()
        maven { url "https://nexus.ala.org.au/content/groups/public/" }
        maven { url "https://repo.grails.org/grails/core" }
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "org.apache.grails:grails-gradle-plugins:$grailsGradlePluginVersion"
//        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:3.3.4"
    }
}

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.apache.grails.gradle.grails-plugin"
//apply plugin:"asset-pipeline"
apply plugin:"org.apache.grails.gradle.grails-gsp"
apply plugin: 'maven-publish'


group 'org.grails.plugins'

repositories {
    maven { url "https://nexus.ala.org.au/content/groups/public/" }
    maven { url "https://repo.grails.org/grails/core" }
    mavenCentral()
    mavenLocal()
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

//dependencyManagement {
//    imports {
//        mavenBom "org.grails:grails-bom:$grailsVersion"
//    }
//    applyMavenExclusions false
//}

dependencies {
    developmentOnly("org.springframework.boot:spring-boot-devtools")
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.apache.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-logging"
    implementation "org.apache.grails:grails-rest-transforms"
    implementation "org.apache.grails:grails-databinding"
    implementation "org.apache.grails:grails-services"
    implementation "org.apache.grails:grails-url-mappings"
    implementation "org.apache.grails:grails-interceptors"
    implementation "org.apache.grails:grails-layout"

    implementation "org.apache.grails:grails-cache"
    implementation "org.apache.grails:grails-async"
    implementation "org.apache.grails:grails-scaffolding"
    implementation "org.apache.grails:grails-gsp"
    compileOnly "io.micronaut:micronaut-inject-groovy:3.10.4"
    console "org.apache.grails:grails-console"
    profile "org.apache.grails.profiles:web-plugin"
//    runtime "com.bertramlabs.plugins:asset-pipeline-grails:3.3.4"
    testImplementation "io.micronaut:micronaut-inject-groovy:3.10.4"
    testImplementation("org.apache.grails:grails-testing-support-datamapping") {
        exclude group: 'org.spockframework'
    }
    testImplementation "org.mockito:mockito-core"
    testImplementation("org.apache.grails:grails-testing-support-web") {
        exclude group: 'org.spockframework'
    }
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    implementation platform("org.spockframework:spock-bom:2.3-groovy-4.0")
    testImplementation "org.spockframework:spock-core"
    testImplementation "org.spockframework:spock-junit4"

    implementation project(':userdetails-service-client')
    testImplementation "com.squareup.retrofit2:retrofit-mock:2.9.0"

    implementation 'org.apereo.cas.client:cas-client-core:4.0.4'
    implementation 'au.org.ala.grails:interceptor-annotation-matcher:2.0.0-SNAPSHOT'
    implementation 'au.org.ala:ala-cas-client:4.0.0-SNAPSHOT'

    implementation(project(':ala-security-common')) {}

    implementation(pac4j.oidc)
    implementation(pac4j.jakartaee)
    implementation(pac4j.jakartaee.support)

    // Not required but this plugin can react to the presence of Spring Session
    compileOnly 'org.springframework.session:spring-session-core'
    compileOnly 'org.springframework.session:spring-session-data-mongodb'
    compileOnly 'org.springframework.boot:spring-boot-starter-data-mongodb'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    compileOnly "org.springframework.boot:spring-boot-configuration-processor"

    implementation group: 'com.github.ben-manes.caffeine', name: 'caffeine', version: '2.7.0'

}

compileGroovy {
    groovyOptions.javaAnnotationProcessing = true
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

compileJava.dependsOn(processResources)

bootRun {
    ignoreExitValue true
    jvmArgs(
            '-Dspring.output.ansi.enabled=always',
            '-noverify',
            '-XX:TieredStopAtLevel=1',
            '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(Test) {
    useJUnitPlatform()
}
// enable if you wish to package this plugin as a standalone application
bootJar.enabled = false

publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.toString().endsWith('-SNAPSHOT') ? 'snapshots' : 'releases' }"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from components.java

            pom {
                name = 'ALA Auth Plugin'
                description = 'Authentication for ALA Apps'
                url = 'https://github.com/AtlasOfLivingAustralia/ala-auth-plugin'
                licenses {
                    license {
                        name = 'MPL-1.1'
                        url = 'https://www.mozilla.org/en-US/MPL/1.1/'
                    }
                }
                developers {
                    developer {
                        id = 'sbearcsiro'
                        name = 'Simon Bear'
                        email = 'simon.bear@csiro.au'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/AtlasOfLivingAustralia/ala-auth-plugin.git'
                    developerConnection = 'scm:git:ssh://github.com:AtlasOfLivingAustralia/ala-auth-plugin.git'
                    url = 'https://github.com/AtlasOfLivingAustralia/ala-auth-plugin/tree/main'
                }
            }

        }
    }
}
