---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.ws.security
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
management:
    endpoints:
        enabled-by-default: false

#    ### Mandatory
#    - ```security.apikey.check.serviceUrl``` - URL of the API Key service endpoint, up to and including the key parameter name. E.g. https://auth.ala.org.au/apikey/ws/check?apikey=
#
#    ### Optional
#    - ```security.apikey.ip.whitelist``` - comma separated list of IP Addresses that are exempt from the API key security check.
#    - ```security.apikey.header.override ``` - override the default request header name (apiKey) to use a different name.


security:
    cas:
        logout: https://nectar-auth-dev.ala.org.au/cas/logout
    jwt:
        jwkUrl: https://nectar-auth-dev.ala.org.au/cas/oidc/jwks
        enabled: true
    legacy:
        whitelist:
            #comma separated list of IP Addresses that are exempt from the API key security check.
            ip: ''
            enabled: false
            userId: '1'
            roles:
                - 'ROLE_ADMIN'
        apikey:
            serviceUrl:
            enabled: false
            userId: '1'
            roles:
                - 'ROLE_ADMIN'